# Use this file as an example if you need help writing your Compose files.
# The commented-out parts may or may not be relevant to your setup.

services:
  vpn:
    image: dovpn
    build: .
    container_name: openvpn
    cap_add: 
      - NET_ADMIN
    devices: 
      - /dev/net/tun:/dev/net/tun
    environment:
      - SUBNETS=$SUBNETS
      - HTTP_PROXY=on
      - SOCKS_PROXY=on
      # - PROXY_USERNAME_SECRET=username # <-- If used, these must match the name of a
      # - PROXY_PASSWORD_SECRET=password # <-- secret (NOT the file used by the secret)
    volumes: 
      - $VPNDIR:/data/vpn
    ports:
      - 1080:1080
      - 8088:8080
      - 9091:9091
    restart: unless-stopped
    # secrets:
    #   - username
    #   - password

# secrets:
#   username:
#     file: ~/local/secrets/username
#   password:
#     file: ~/local/secrets/password


  transmission:
    image: linuxserver/transmission
    container_name: transmission
    depends_on:
      - openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
#    volumes:
#      - <Config location>:/config
#      - <Download location>:/downloads
#      - <Watch location>:/watch
    network_mode: container:openvpn      # The addition to add to all containers that you want to route through VPN container
    restart: unless-stopped
  